name: Build BKUpdater App

on:
  push:
  workflow_dispatch:

jobs:
  build-bkupdater:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 18

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Build with Gradle
        run: |
          {
            echo 'org.gradle.parallel=true'
            echo 'org.gradle.vfs.watch=true'
            echo 'org.gradle.jvmargs=-Xmx2048m'
            echo 'android.native.buildOutput=verbose'
          } >> gradle.properties
          sed -i 's/org.gradle.configuration-cache=true//g' gradle.properties
          ./gradlew clean assembleRelease

      - name: Sign App
        run: |
          java -jar "/home/runner/work/BKUpdater/BKUpdater/apksigner.jar" sign  --key "/home/runner/work/BKUpdater/BKUpdater/BKUpdater.pk8" --cert "/home/runner/work/BKUpdater/BKUpdater/BKUpdater.pem"  --v4-signing-enabled false --out "/home/runner/work/BKUpdater/BKUpdater/app/build/outputs/apk/release/app-release-signed.apk" "/home/runner/work/BKUpdater/BKUpdater/app/build/outputs/apk/release/app-release-unsigned.apk"
          
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: BKUpdater.apk
          path: /home/runner/work/BKUpdater/BKUpdater/app/build/outputs/apk/release/app-release-unsigned-signed.apk
          if-no-files-found: error
